# commands
LEFT_1ST = "L1ST"
LEFT_2ND = "L2ND"
RIGHT_1ST = "R1ST"
RIGHT_2ND = "R2ND"
FORWARD = "Z"
REVERSE  = "F"
STOP = "STOP"

# IMG_RESULT
LEFT = "LEFT"
RIGHT = "RIGHT"

# STM responses
ROBOT_COMMAND_COMPLETED = "S11"
ROBOT_READY_TO_PARK = "PARK"

# DATA
PARK_DIST = 20